# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'RxSwiftTest' do
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'RxSwiftExt', :git => "https://github.com/RxSwiftCommunity/RxSwiftExt", :branch => "swift3"
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
